### ISSUE TITLE
Provide a settings plugin to centrally define all Module Names

### ISSUE THREAD

**Issue by jjohannes** [gradlex-org/java-module-dependencies#114]
Right now, there is quite some trouble with the fact that the plugin does not know the names of the other local modules located in other subprojects. This issue is about how to improve this without breaking [project isolation](https://gradle.github.io/configuration-cache/).

The underlying issue is that the `module-info.java` files are parsed as part of the configuration phase of each project individually. And only after they are parsed the real name is known. This is too late. The name should ideally be known during the "initialization phase" (when `setting.gradle` is parsed). That is the place where also the _project names_ get defined. Right now, there is a certain duplication already, because the _project names_ you define in `settings.gradle` need to be similar to the _Module Names_ for the current mechanism to work.

The idea now is to allow users to apply this plugin in `settings.gradle` and then define all Names there or maybe even get them automatically by parsing `main/java/module-info.java` files early. Also, this should allow defining the "group" of the projects early, wich we need to determine the "capabilities" of dependencies that point at another "feature variant" of a project. The `getGroup` we currently have to call on other projects is breaking project isolation.

This is how it could look like:

**settings.gradle.kts**
```
plugins {
  id("org.gradlex.java-module-depedencies"
}

javaModules { // our own extension, use instead of 'include(...)'
   // Module is in folder lib - searches in 'src/*/java' for 'module-info.java' files
  module("lib")

  // Individualised
  module("lib") {
    plugin("java-library") // apply plugin to the module to avoid separate 'build.gradle' only for this
    group = "org.example"  // define group early in settings so that all projects know all groups
    artifact = "lib-x"     // Gradle project name, corresponds to artifact in "group:artifact" coordinates
    moduleInfoPaths.add("src") // custom location for module-info
  }

  // Auto-include all
  // - searches in '<subfloder>/src/*/java' for 'module-info.java' files
  // - each <subfloder> that has at least one 'module-info.java' becomes subproject
  directory("modules") {
    group = "org.example"
    plugin("java-library")  // plugins for all modules
    module("app") { ... }   // individualise module is needed
  }
}
```

In the implementation, this will do the corresponding `include(...)`s but also fill a central _module identity cache_ with all the information. If the plugin is used in settings, the "guessing" mechanism based on the prefix of Module Names is turned off and the _module identity cache_ is used instead.

**Comment by TheGoesen** [comment]
After reading a bit through the gradle API and documentation: It seems to me that the Initialization phase is too early to do anything smart. Basically all we  have at this point is the projects and their names. We dont know if these projects are even java projects and we don't know where their sources are. 
So as a matter of fact nothing changes: 

- using the current approach (and isolated projects) we only have access to the project name/root project/project dir... because these are the only things that are permitted in isolated builds. 
- Applying a settings plugin we also only have access to these properties, because the java plugin hasn't been applied yet.

So in both cases we can access some sort of config file relative to the root dir like this: `new File(getProject().getRootDir(), "gradle/modules.properties")`, but cant reliable find or iterate over sourcesets.

So I suggest one could try to hack around using a build-service. In the (isolated) configuration phase all projects throw their own jpms names into the buildservice/central module identity cache (in parallel).
Resolving the (dependency)configuration should  always happen after that is complete, so access the buildservice lazy and it just works?

Would have to play around a bit to check for sideeffects,
Best regards

**Comment by TheGoesen** [comment]
Actually there is another even bigger issue at hand, which is configuration on demand. https://docs.gradle.org/current/userguide/multi_project_configuration_and_execution.html
In that case gradle needs to be fed the info what projects to actually configure. Usually gradle gets this info from the dependencies, which point to a project. But if you only have your `requires myorg.legacy.whatever` then really your only options are that there is a either a function to calculate a project name from the jpms name, or a mapping already exists at that point. So that puts the idea of the settings plugin back on the menu, with obvious the downside that it cant see the correct location of the module-info file, so that requires guessing or double configuration...

**Comment by jjohannes** [comment]
Version `1.7` now [contains a Settings DSL](https://github.com/gradlex-org/java-module-dependencies?tab=readme-ov-file#project-structure-definition-when-using-this-plugin-as-settings-plugin) as described above. If used, the plugin is fully compatible with project isolation and no longer relies on names/groups to align. The only assumption the plugin still makes is that, if you use [addition Feature Variants with Capabilities](https://docs.gradle.org/current/userguide/feature_variants.html) (which includes [Test Fixtures](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures)), the sources folder name has to map to the capability name (e.g. `src/testFixtures/java` maps to `<group>:<artifact>-test-fixtures`), which is what Gradle does by default if you use `registerFeature` or the `java-test-fixtures` plugin. With this, test fixtures work even nicer with project isolation than it currently does in plain Gradle  - see https://github.com/gradle/gradle/issues/27872#issuecomment-2151775051.

If the plugin is used in the "traditional way" though, nothing changes.

> one could try to hack around using a build-service. In the (isolated) configuration phase all projects throw their own jpms names into the buildservice/central module identity cache (in parallel).

For using the plugin without the settings part, something like this would be needed. That is, after all projects are configured, but before dependency resolution starts as part of the task graph building, all information would need to be gathered. Before the dependencies are actually created. Which **should** be done late as we use Providers and `withDependencies { }` to create them. However:

1. This is always fragile in Gradle: other plugins or build configuration can easily break the laziness without Gradle giving you a hint
2. I don't think that a hook exists for this. Build services are for task execution. Not to synchronize something during build configuration. And my understanding is that with _project isolation_, eventually all subprojects will configure in parallel. I assume they will only "wait for each other" once the task graph starts establishing relationships between the subprojects. But I don't think there is a "global synchronization" to hook into (but I might be wrong).
