### ISSUE TITLE
Improve how the Settings plugin does the directory listing

### ISSUE THREAD

**Issue by TheGoesen** [gradlex-org/java-module-dependencies#128]
While writing test cases I discovered that the settings plugin will cause will cause configuration cache misses.
If you apply the settings plugin and compile the same module 2 times in a row you will get:
`Calculating task graph as configuration cache cannot be reused because directory '.' has changed.`
So because the Settings plugin just operates on Files instead of using valueSources doing about anything can cause a configuration cache miss, especially deleting or creating the build directory

**Comment by TheGoesen** [comment]
so the problem does not lie that much in the settings plugin generally but more in the "directory" functionality. Since directory list list all files including the build directory this functionality can be a bit problematic

**Comment by jjohannes** [comment]
In my practical experience this is not problematic. The main use of the configuration cache is running the same build locally several times in a row. The content of the `'.'` directory usually does not change while doing so. I use this or similar approaches to automatically include projects in several projects and it works well with the configuration cache enabled.

I don't know how this could be done in a different way. But if there is, please share a concrete suggestions.
(Otherwise, I would close this issue.)

**Comment by jjohannes** [comment]
Thank you for the context. In that case, I am happy to accept a contribution that improve this through a _value source_ that filters out reasonable entries in the listing. Maybe this should be configurable, but I think having a reasonable default exclusion that always applies would also be a good first step. I think a reasonable default would be:
- everything that is **not** a folder
- the **build** folder
- folders starting with **.** (hidden folders)
