### ISSUE TITLE
Improve performance of ApplyPluginsAction

### ISSUE THREAD

**Issue by TheGoesen** [gradlex-org/java-module-dependencies#135]
So this is probably just me being a dick for no real reason buuuut:
Currently this Plugin adds an ApplyPluginAction for each Project/module. Each ApplyPluginAction does a check if its running on the "correct" module/Plugin.  This results in O(n) ApplyPluginActions which executions scales as O (n^2) 
This should be easily replaceable with the following axiom: Apply only one ApplyPluginAction, that has a HashSet containing all projects to run on. Now you have 1 ApplyPluginAction whose exection scales as O(nlogn) 
These things usually get very obnoxius if you get around number like 10.000, which as of gradle projects requiring module-info that is probably not a pressing issue, but in my lifetime as a developer i had to apply this specific fix so many times....
Yada yada can provide a prototype when the other stuff is merged, is probably just me being picky for no good reason.

**Comment by jjohannes** [comment]
Yes thanks. I was focused on finding solutions that avoids additional state. To avoid having to think about where such state is allowed to go. This is because I am still not sure which state is allowed when/how with the isolated projects feature. Because the map would be saved in the settings context and then accessed in the context of each project. But it is very likely possible to do.
I am happy to review a contribution in this area.
